force-app/main/default/objects/Opportunity/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Won_Date__c.field-meta.xml
<CustomField>
    <fullName>Won_Date__c</fullName>
    <label>Won Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OpportunityHandler.cls
public with sharing class OpportunityHandler {
    public static void handleAfterInsert(List<Opportunity> newOpportunities) {
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        
        for (Opportunity opp : newOpportunities) {
            if (opp.Amount >100) {
                opp.Priority__c = 'High';
                opportunitiesToUpdate.add(opp);
            }
        }
        
        if (!opportunitiesToUpdate.isEmpty()) {
            update opportunitiesToUpdate;
        }

        
    }
    
    public static void handleAfterUpdate(
    List<Opportunity> updatedOpportunities,
    Map<Id, Opportunity> oldMap
) {
    List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();

    for (Opportunity opp : updatedOpportunities) {

        Opportunity oldOpp = oldMap.get(opp.Id);

        // Scenario 2: Amount changed and > 100
        if (opp.Amount != oldOpp.Amount && opp.Amount > 100) {
            opp.Priority__c = 'High';
            opportunitiesToUpdate.add(opp);
        }

        // Scenario 3: Stage moved to Closed Won
        if (opp.StageName == 'Closed Won' &&
            oldOpp.StageName != 'Closed Won') {

            opp.Won_Date__c = Date.today();
            opportunitiesToUpdate.add(opp);
        }
    }

    if (!opportunitiesToUpdate.isEmpty()) {
        update opportunitiesToUpdate;
    }
}

public static void handleBeforeUpdate(List<Opportunity> updatedOpportunities, Map<Id, Opportunity> oldMap) {
    for (Opportunity opp : updatedOpportunities) {
        Opportunity oldOpp = oldMap.get(opp.Id);

        // Scenario 1: Stage moved to Closed won
        if (opp.StageName == 'Closed Won' &&
            oldOpp.StageName != 'Closed Won') {

            opp.CloseDate = Date.today();
        }
    }

}
}